### ISSUE TITLE
bark推送失败

### ISSUE THREAD

**Issue by Stev00** [aefa6/QinglongScript#1]
兄弟，青龙使用[每天60s读懂世界.py]，使用bark推送 
log显示 bark 推送失败！

实际看下看来是notify.py里面的response=requests.post(url).json()这一步出现问题
详细log为{'code': 431, 'message': 'Request Header Fields Too Large', 'timestamp': 1690385013}

大佬看下怎么解决。。。。

**Comment by aefa6** [comment]
我改成了分段推送，应该是字段太长导致无法推送了，因为我没测试过bark，如果还报错再反馈吧。

**Comment by Stev00** [comment]
第一部分推送成功了，第7条开始显示bark推送失败

**Comment by aefa6** [comment]
> 第一部分推送成功了，第五条开始显示bark推送失败

青龙日志看一下，企业微信推送和sever酱都是没问题的，没有日志我没法知道是什么原因
我把第二段推送也加上标题了，看下是不是不报错了，如果是的话说明bark推送不可以没有标题…

**Comment by Stev00** [comment]
'\n'.join(content[12:]),'\n'.join(content[7:12]),'\n'.join(content[:7])
试了下，上面这个可以

**Comment by Martinxux** [comment]
![image](https://github.com/aefa6/QinglongScript/assets/90446788/cf708b50-b725-461d-a3aa-2ded95897105)
企业微信推送，合并推送会有报错，如图所示

**Comment by aefa6** [comment]
> ![image](https://private-user-images.githubusercontent.com/90446788/310054869-cf708b50-b725-461d-a3aa-2ded95897105.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MzI1ODcsIm5iZiI6MTcwOTYzMjI4NywicGF0aCI6Ii85MDQ0Njc4OC8zMTAwNTQ4NjktY2Y3MDhiNTAtYjcyNS00NjFkLWEzYWEtMmRlZDk1ODk3MTA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDA5NTEyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5NTcyZmM5ZGRhMGZkYzQxOWU2ZDMxMmIzMjYwNTQ5NmQyOTdkZDVkZTY2MDNiNDQxNGNjMDNjMWJjYjQ0YzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QzKhLErjcPEWxafC_LQOSUGx75eV8GMtyZkp8H3Ei90) 企业微信推送，合并推送会有报错，如图所示

对的，所以我提供了分片推送。报错就用分片推送吧。

**Comment by Martinxux** [comment]
> > ![image](https://private-user-images.githubusercontent.com/90446788/310054869-cf708b50-b725-461d-a3aa-2ded95897105.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MzI1ODcsIm5iZiI6MTcwOTYzMjI4NywicGF0aCI6Ii85MDQ0Njc4OC8zMTAwNTQ4NjktY2Y3MDhiNTAtYjcyNS00NjFkLWEzYWEtMmRlZDk1ODk3MTA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDA5NTEyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5NTcyZmM5ZGRhMGZkYzQxOWU2ZDMxMmIzMjYwNTQ5NmQyOTdkZDVkZTY2MDNiNDQxNGNjMDNjMWJjYjQ0YzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QzKhLErjcPEWxafC_LQOSUGx75eV8GMtyZkp8H3Ei90) 企业微信推送，合并推送会有报错，如图所示
> 
> 对的，所以我提供了分片推送。报错就用分片推送吧。

好的，我是看您上面说微信可以合并😂，分开就是有点丑

**Comment by aefa6** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/90446788/310054869-cf708b50-b725-461d-a3aa-2ded95897105.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MzI1ODcsIm5iZiI6MTcwOTYzMjI4NywicGF0aCI6Ii85MDQ0Njc4OC8zMTAwNTQ4NjktY2Y3MDhiNTAtYjcyNS00NjFkLWEzYWEtMmRlZDk1ODk3MTA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDA5NTEyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5NTcyZmM5ZGRhMGZkYzQxOWU2ZDMxMmIzMjYwNTQ5NmQyOTdkZDVkZTY2MDNiNDQxNGNjMDNjMWJjYjQ0YzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QzKhLErjcPEWxafC_LQOSUGx75eV8GMtyZkp8H3Ei90) 企业微信推送，合并推送会有报错，如图所示
> > 
> > 
> > 对的，所以我提供了分片推送。报错就用分片推送吧。
> 
> 好的，我是看您上面说微信可以合并😂，分开就是有点丑

我用的是微信机器人
