### ISSUE TITLE
你可能对环境变量有什么误解

### ISSUE THREAD

**Issue by Ocyss** [aefa6/QinglongScript#2]
环境变量，不是直接去修改源文件。。。
py的话可以使用
```python
for ck in os.getenv('Cookie').split("&"):
```
js好像是这个
```js
process.env.COOKIE
```
你自己多试试吧，不然拉库就又覆盖掉之前的变量了，不拉万一没更新出了什么问题。

**Comment by aefa6** [comment]
的确，这个不是修改环境变量，是直接改源文件，因为我怕变量名冲突，而且也为了让依赖更少一点。

**Comment by aefa6** [comment]
暂时我还是不想用环境变量，在文件里改内容并不麻烦还能减少冲突，就先这么用吧。
