### ISSUE TITLE
辛苦大佬把天翼云盘的手动输入账号密码改成变量的形式

### ISSUE THREAD

**Issue by iuyaa** [aefa6/QinglongScript#6]
辛苦大佬把天翼云盘的手动输入账号密码改成变量的形式，订阅一更新，账号密码就没了🤣

**Comment by jm3720343** [comment]
天翼云盘脚本失效了，只能领一次

**Comment by aefa6** [comment]
好像大家都比较喜欢变量的形式，但是我之前试过用变量如果你还挂着JDcookie可能会冲突，所以一直没加，另外tianyiyun好久没玩了，也没能力修，不好意思哈。建议GitHub找替代。
